import ravioli from '../assets/img/ravioli.png';
import lasagna from '../assets/img/lasagna.avif'
import lasagnaSheets from '../assets/img/lasagna.png';
import carTaglia from '../assets/img/carTagliatelle.png';
import carSpa from '../assets/img/carSpaghetti.png';
import carPenne from '../assets/img/carPenne.png'
import betTaglia from '../assets/img/betTagliatelle.png';
import betSpa from '../assets/img/betSpaghetti.png';
import betPenne from '../assets/img/betPenne.png';
import bwgTaglia from '../assets/img/bwgTagliatelle.png';
import bwgSpa from '../assets/img/bwgSpaghetti.png';
import bwgPenne from '../assets/img/bwgPenne.png';
import oatTaglia from '../assets/img/oatTagliatelle.png';
import oatSpa from '../assets/img/oatSpaghetti.png';
import oatPenne from '../assets/img/oatPenne.png';
import barSpa from '../assets/img/barleySpaghetti.png';
import barPenne from '../assets/img/barleyPenne.png';
import barTaglia from '../assets/img/barTagliatelle.png';
import pdsPappar from '../assets/img/pdsPappar.png';
import pPappar from '../assets/img/pPappar.png';
import pTaglia from '../assets/img/pTaglia.png';
import pdsTaglia from '../assets/img/pdsTagliatelle.png'

export const PRODUCTS = [
  {
    id: 'bulk-fully-cooked-lasagna',
    slug: 'bulk-fully-cooked-lasagna',
    name: 'Bulk Fully Cooked Lasagna',
    category: 'lasagna',
    ingredient: 'classic',
    pastaType: 'lasagna',
    packSize: 'Per kg',
    price: 1100,
    unit: 'kg',
    description: 'Ready-to-heat fully cooked lasagna, prepared with premium ingredients for commercial kitchens and foodservice operations.',
    cookingTime: '10 min (reheat)',
    suggestedDishes: ['Buffet service', 'Catering events', 'Restaurant plating'],
    image: lasagna,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'classic-lasagna-sheets',
    slug: 'classic-lasagna-sheets',
    name: 'Classic Lasagna Sheets',
    category: 'lasagna',
    ingredient: 'durum-semolina',
    pastaType: 'lasagna',
    packSize: '500 g',
    price: 699,
    unit: 'pack',
    description: 'Ready-to-use fresh lasagna sheets for layering with your favorite sauces and fillings. No pre-boiling required.',
    cookingTime: '20-25 min (baked)',
    suggestedDishes: ['Classic meat lasagna', 'Vegetable lasagna', 'Spinach and ricotta'],
    image: lasagnaSheets,
    bestSeller: true,
    featured: true,
  },
  {
    id: 'carrot-tagliatelle',
    slug: 'carrot-tagliatelle',
    name: 'Carrot Tagliatelle',
    category: 'specialty',
    ingredient: 'carrot',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Vibrant tagliatelle pasta made with fresh carrot puree.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Light vegetable sauces', 'Olive oil and herbs', 'Cold pasta salad'],
    image: carTaglia,
    bestSeller: true,
    featured: true,
  },
  {
    id: 'carrot-spaghetti',
    slug: 'carrot-spaghetti',
    name: 'Carrot Spaghetti',
    category: 'specialty',
    ingredient: 'carrot',
    pastaType: 'spaghetti',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Vibrant spaghetti pasta made with fresh carrot puree.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Light vegetable sauces', 'Olive oil and herbs', 'Cold pasta salad'],
    image: carSpa,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'carrot-penne',
    slug: 'carrot-penne',
    name: 'Carrot Penne',
    category: 'specialty',
    ingredient: 'carrot',
    pastaType: 'penne',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Vibrant penne pasta made with fresh carrot puree.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Light vegetable sauces', 'Olive oil and herbs', 'Cold pasta salad'],
    image: carPenne,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'beetroot-tagliatelle',
    slug: 'beetroot-tagliatelle',
    name: 'Beetroot Tagliatelle',
    category: 'specialty',
    ingredient: 'beetroot',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Striking ruby-red tagliatelle infused with fresh beetroot.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Goat cheese', 'Walnuts', 'Citrus herb sauces'],
    image: betTaglia,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'beetroot-spaghetti',
    slug: 'beetroot-spaghetti',
    name: 'Beetroot Spaghetti',
    category: 'specialty',
    ingredient: 'beetroot',
    pastaType: 'spaghetti',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Striking ruby-red spaghetti infused with fresh beetroot.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Goat cheese', 'Walnuts', 'Citrus herb sauces'],
    image: betSpa,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'beetroot-penne',
    slug: 'beetroot-penne',
    name: 'Beetroot Penne',
    category: 'specialty',
    ingredient: 'beetroot',
    pastaType: 'penne',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Striking ruby-red penne infused with fresh beetroot.',
    cookingTime: '6-8 min',
    suggestedDishes: ['Goat cheese', 'Walnuts', 'Citrus herb sauces'],
    image: betPenne,
    bestSeller: true,
    featured: false,
  },
  {
    id: 'brown-whole-grain-tagliatelle',
    slug: 'brown-whole-grain-tagliatelle',
    name: 'Brown Whole Grain Tagliatelle',
    category: 'whole-grain',
    ingredient: 'brown-whole-grain',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Nutritious whole grain tagliatelle pasta rich in fiber, with a hearty texture and wholesome flavor for health-conscious cooking.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Hearty meat sauces', 'Vegetable ragu', 'Mediterranean style'],
    image: bwgTaglia,
    bestSeller: false,
    featured: true,
  },
  {
    id: 'brown-whole-grain-spaghetti',
    slug: 'brown-whole-grain-spaghetti',
    name: 'Brown Whole Grain Spaghetti',
    category: 'whole-grain',
    ingredient: 'brown-whole-grain',
    pastaType: 'spaghetti',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Nutritious whole grain spaghetti pasta rich in fiber, with a hearty texture and wholesome flavor for health-conscious cooking.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Hearty meat sauces', 'Vegetable ragu', 'Mediterranean style'],
    image: bwgSpa,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'brown-whole-grain-penne',
    slug: 'brown-whole-grain-penne',
    name: 'Brown Whole Grain Penne',
    category: 'whole-grain',
    ingredient: 'brown-whole-grain',
    pastaType: 'penne',
    packSize: '500 g',
    price: 724,
    unit: 'pack',
    description: 'Nutritious whole grain penne pasta rich in fiber, with a hearty texture and wholesome flavor for health-conscious cooking.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Hearty meat sauces', 'Vegetable ragu', 'Mediterranean style'],
    image: bwgPenne,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'oat-tagliatelle',
    slug: 'oat-tagliatelle',
    name: 'Oat Tagliatelle',
    category: 'whole-grain',
    ingredient: 'oat',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Creamy oat-based pasta with a smooth texture and mild, comforting flavor. Naturally high in protein and fiber.',
    cookingTime: '7-9 min',
    suggestedDishes: ['Creamy Alfredo', 'Pesto', 'Butter and sage'],
    image: oatTaglia,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'oat-spaghetti',
    slug: 'oat-spaghetti',
    name: 'Oat Spaghetti',
    category: 'whole-grain',
    ingredient: 'oat',
    pastaType: 'spaghetti',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Creamy oat-based spaghetti with a smooth texture and mild flavor.',
    cookingTime: '7-9 min',
    suggestedDishes: ['Creamy Alfredo', 'Pesto', 'Butter and sage'],
    image: oatSpa,
    bestSeller: true,
    featured: false,
  },
  {
    id: 'oat-penne',
    slug: 'oat-penne',
    name: 'Oat Penne',
    category: 'whole-grain',
    ingredient: 'oat',
    pastaType: 'penne',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Creamy oat-based penne with a smooth texture and mild flavor.',
    cookingTime: '7-9 min',
    suggestedDishes: ['Creamy Alfredo', 'Pesto', 'Butter and sage'],
    image: oatPenne,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'durum-tagliatelle',
    slug: 'pure-durum-semolina-tagliatelle',
    name: 'Pure Durum Semolina Tagliatelle',
    category: 'premium',
    ingredient: 'durum-semolina',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 1024,
    unit: 'pack',
    description: 'Our finest pasta made from 100% premium durum wheat semolina.',
    cookingTime: '7-9 min',
    suggestedDishes: ['Classic Bolognese', 'Traditional ragu', 'Truffle and parmesan'],
    image: pdsTaglia,
    bestSeller: false,
    featured: true,
  },
  {
    id: 'durum-pappardelle',
    slug: 'pure-durum-semolina-pappardelle',
    name: 'Pure Durum Semolina Pappardelle',
    category: 'premium',
    ingredient: 'durum-semolina',
    pastaType: 'pappardelle',
    packSize: '500 g',
    price: 1024,
    unit: 'pack',
    description: 'Our finest pasta made from 100% premium durum wheat semolina.',
    cookingTime: '7-9 min',
    suggestedDishes: ['Classic Bolognese', 'Traditional ragu', 'Truffle and parmesan'],
    image: pdsPappar,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'gourmet-ravioli',
    slug: 'gourmet-ravioli',
    name: 'Gourmet Ravioli',
    category: 'filled',
    ingredient: 'assorted',
    pastaType: 'ravioli',
    shapes: ['Cheese', 'Spinach', 'Meat filling'],
    packSize: '250 g',
    price: 480,
    unit: 'pack',
    description: 'Handcrafted ravioli filled with your choice of premium cheese, fresh spinach, or savory meat. Delicate pasta pillows of perfection.',
    cookingTime: '4-6 min',
    suggestedDishes: ['Brown butter and sage', 'Marinara', 'Creamy parmesan'],
    image: ravioli,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'ricotta-filled-pasta',
    slug: 'ricotta-filled-pasta',
    name: 'Ricotta Filled Pasta',
    category: 'filled',
    ingredient: 'ricotta',
    pastaType: 'ravioli',
    shapes: ['Ricotta cheese filling'],
    packSize: '250 g',
    price: 650,
    unit: 'pack',
    description: 'Delicate pasta filled with creamy ricotta cheese and a hint of nutmeg. A classic Italian delicacy ready in minutes.',
    cookingTime: '4-6 min',
    suggestedDishes: ['Tomato basil sauce', 'Pesto Genovese', 'Simple olive oil'],
    image: pPappar,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'premium-barley-tagliatelle',
    slug: 'premium-barley-tagliatelle',
    name: 'Premium Barley Tagliatelle',
    category: 'premium',
    ingredient: 'barley',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 924,
    unit: 'pack',
    description: 'Premium barley tagliatelle crafted from nutritious barley flour, offering a rich nutty flavor and broad ribbons ideal for hearty sauces.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Wild boar ragu', 'Rich meat sauces', 'Creamy mushroom sauce'],
    image: pTaglia,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'premium-barley-pappardelle',
    slug: 'premium-barley-pappardelle',
    name: 'Premium Barley Pappardelle',
    category: 'premium',
    ingredient: 'barley',
    pastaType: 'pappardelle',
    packSize: '500 g',
    price: 924,
    unit: 'pack',
    description: 'Premium barley pappardelle made with wholesome barley flour, featuring extra-wide ribbons that pair beautifully with rich and slow-cooked sauces.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Wild boar ragu', 'Rich meat sauces', 'Creamy mushroom sauce'],
    image: pPappar,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'barley-tagliatelle',
    slug: 'barley-tagliatelle',
    name: 'Barley Tagliatelle',
    category: 'whole-grain',
    ingredient: 'barley',
    pastaType: 'tagliatelle',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Ancient grain barley tagliatelle with a nutty, robust flavor and excellent nutritional profile. Perfect for rich sauces and hearty dishes.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Mushroom sauces', 'Hearty stews', 'Grain bowls'],
    image: barTaglia,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'barley-spaghetti',
    slug: 'barley-spaghetti',
    name: 'Barley Spaghetti',
    category: 'whole-grain',
    ingredient: 'barley',
    pastaType: 'spaghetti',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Ancient grain barley spaghetti with a nutty, robust flavor and excellent nutritional profile. A wholesome alternative to traditional pasta.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Mushroom sauces', 'Hearty stews', 'Grain bowls'],
    image: barSpa,
    bestSeller: false,
    featured: false,
  },
  {
    id: 'barley-penne',
    slug: 'barley-penne',
    name: 'Barley Penne',
    category: 'whole-grain',
    ingredient: 'barley',
    pastaType: 'penne',
    packSize: '500 g',
    price: 824,
    unit: 'pack',
    description: 'Ancient grain barley penne with a nutty, robust flavor and excellent nutritional profile. Ideal for thick sauces and baked pasta dishes.',
    cookingTime: '8-10 min',
    suggestedDishes: ['Mushroom sauces', 'Hearty stews', 'Grain bowls'],
    image: barPenne,
    bestSeller: false,
    featured: false,
  },
];